In [38]:
import numpy as np
import pandas as pd
import os
import datetime

In [25]:
files = os.listdir('C:\\Users\\gosti\\Downloads\\Telegram Desktop\\results\\results')

In [26]:
dfs = []
for f in files:
    df1 = pd.read_csv('C:\\Users\\gosti\\Downloads\\Telegram Desktop\\results\\results\\Adygeja_Resp_2022-03-20.csv', encoding = 'utf-8')
    dfs.append(df1)

In [53]:
data = pd.concat(dfs)

In [28]:
results = pd.read_excel(r'C:\\Users\\gosti\\Downloads\\Telegram Desktop\\01_04_D_New_loans_subj.xlsx')

In [54]:
data.head()

Unnamed: 0             obj hash              name              reg num  \
0           0  3793294491059705333  contracts_output  1010101008321000004   
1           1 -4348589201702449915  contracts_output  1010400570119000014   
2           2  7104910193783858246  contracts_output  1010400570119000016   
3           3 -1585908082334183978  contracts_output  1010400570119000027   
4           4 -3961364508861951295  contracts_output  1010400570119000027   

   customer inn   sign date  suppliers count  supplier inn     st date  \
0     101010083  2021-09-27                1  1.052336e+10  2021-09-27   
1     104005701  2019-08-08                1  1.050111e+10  2021-01-01   
2     104005701  2019-09-03                1  1.050530e+08  2021-01-01   
3     104005701  2019-09-24                1  2.312263e+09  2021-01-01   
4     104005701  2019-09-24                1  2.312263e+09  2021-01-01   

     end date      price  enforcement     amount  \
0  2021-12-31  500000.00            1   25000.00   
1  2021-12-31  933718.40            1  373500.00   
2  2021-12-31  125125.25            0    6256.26   
3  2021-12-31  355169.38            1   19878.00   
4  2021-12-31  388020.88            1   19878.00   

                                                 doc protocol date  
0  Протокол рассмотрения единственной заявки на у...    2021-09-14  
1  Протокол подведения итогов электронного аукцио...    2019-07-26  
2  Протокол подведения итогов электронного аукцио...    2019-08-22  
3  Протокол подведения итогов электронного аукцио...    2019-09-12  
4  Протокол подведения итогов электронного аукцио...    2019-09-12

In [55]:
data = data.drop(columns=data[['customer inn', 'supplier inn', 'protocol date', 'doc']])

In [56]:
data = data.assign(bg=data.amount / data.price)
data

Unnamed: 0             obj hash              name              reg num  \
0              0  3793294491059705333  contracts_output  1010101008321000004   
1              1 -4348589201702449915  contracts_output  1010400570119000014   
2              2  7104910193783858246  contracts_output  1010400570119000016   
3              3 -1585908082334183978  contracts_output  1010400570119000027   
4              4 -3961364508861951295  contracts_output  1010400570119000027   
...          ...                  ...               ...                  ...   
6359        6359 -4906157625135826188  contracts_output  3010800386421000022   
6360        6360 -8165939967697628755  contracts_output  3010800386421000022   
6361        6361  -725861710018253917  contracts_output  3010800386421000025   
6362        6362 -2881107635711435453  contracts_output  3010800386421000025   
6363        6363 -1158808855413502250  contracts_output  3010800386422000008   

       sign date  suppliers count     st date    end date       price  \
0     2021-09-27                1  2021-09-27  2021-12-31   500000.00   
1     2019-08-08                1  2021-01-01  2021-12-31   933718.40   
2     2019-09-03                1  2021-01-01  2021-12-31   125125.25   
3     2019-09-24                1  2021-01-01  2021-12-31   355169.38   
4     2019-09-24                1  2021-01-01  2021-12-31   388020.88   
...          ...              ...         ...         ...         ...   
6359  2021-10-04                1  2021-10-04  2022-01-31  1452000.00   
6360  2021-10-04                1  2021-10-04  2022-01-31  1452000.00   
6361  2021-10-25                1  2021-10-25  2021-12-31   106600.00   
6362  2021-10-25                1  2021-10-25  2021-12-31   106599.90   
6363  2022-02-21                1  2022-03-01  2022-07-31   520192.00   

      enforcement     amount        bg  
0               1   25000.00  0.050000  
1               1  373500.00  0.400014  
2               0    6256.26  0.050000  
3               1   19878.00  0.055968  
4               1   19878.00  0.051229  
...           ...        ...       ...  
6359            0   72600.00  0.050000  
6360            0   72600.00  0.050000  
6361            1    5500.00  0.051595  
6362            1    5500.00  0.051595  
6363            0   26009.60  0.050000  

[1088244 rows x 12 columns]

In [57]:
data = data.drop_duplicates()[:100]
data

Unnamed: 0             obj hash              name              reg num  \
0            0  3793294491059705333  contracts_output  1010101008321000004   
1            1 -4348589201702449915  contracts_output  1010400570119000014   
2            2  7104910193783858246  contracts_output  1010400570119000016   
3            3 -1585908082334183978  contracts_output  1010400570119000027   
4            4 -3961364508861951295  contracts_output  1010400570119000027   
..         ...                  ...               ...                  ...   
95          95 -7225163988810488269  contracts_output  1010501691421000032   
96          96  3444059651121947372  contracts_output  1010501691421000034   
97          97 -3364522712682730924  contracts_output  1010501691421000036   
98          98  2228551905017172812  contracts_output  1010501691421000037   
99          99   421385556509788594  contracts_output  1010501691421000039   

     sign date  suppliers count     st date    end date      price  \
0   2021-09-27                1  2021-09-27  2021-12-31  500000.00   
1   2019-08-08                1  2021-01-01  2021-12-31  933718.40   
2   2019-09-03                1  2021-01-01  2021-12-31  125125.25   
3   2019-09-24                1  2021-01-01  2021-12-31  355169.38   
4   2019-09-24                1  2021-01-01  2021-12-31  388020.88   
..         ...              ...         ...         ...        ...   
95  2021-03-30                1  2021-03-30  2021-12-01  121091.46   
96  2021-04-05                1  2021-04-05  2021-09-30  929631.00   
97  2021-04-13                1  2021-04-13  2021-12-01    9183.33   
98  2021-04-13                1  2021-04-13  2021-12-01    3309.16   
99  2021-04-27                1  2021-04-27  2021-12-01  510436.00   

    enforcement     amount        bg  
0             1   25000.00  0.050000  
1             1  373500.00  0.400014  
2             0    6256.26  0.050000  
3             1   19878.00  0.055968  
4             1   19878.00  0.051229  
..          ...        ...       ...  
95            0   36509.99  0.301508  
96            1  597620.41  0.642858  
97            0    2755.00  0.300000  
98            0     992.75  0.300001  
99            1  153130.80  0.300000  

[100 rows x 12 columns]

In [58]:
data = data[data.bg <= 1]
data

Unnamed: 0             obj hash              name              reg num  \
0            0  3793294491059705333  contracts_output  1010101008321000004   
1            1 -4348589201702449915  contracts_output  1010400570119000014   
2            2  7104910193783858246  contracts_output  1010400570119000016   
3            3 -1585908082334183978  contracts_output  1010400570119000027   
4            4 -3961364508861951295  contracts_output  1010400570119000027   
..         ...                  ...               ...                  ...   
95          95 -7225163988810488269  contracts_output  1010501691421000032   
96          96  3444059651121947372  contracts_output  1010501691421000034   
97          97 -3364522712682730924  contracts_output  1010501691421000036   
98          98  2228551905017172812  contracts_output  1010501691421000037   
99          99   421385556509788594  contracts_output  1010501691421000039   

     sign date  suppliers count     st date    end date      price  \
0   2021-09-27                1  2021-09-27  2021-12-31  500000.00   
1   2019-08-08                1  2021-01-01  2021-12-31  933718.40   
2   2019-09-03                1  2021-01-01  2021-12-31  125125.25   
3   2019-09-24                1  2021-01-01  2021-12-31  355169.38   
4   2019-09-24                1  2021-01-01  2021-12-31  388020.88   
..         ...              ...         ...         ...        ...   
95  2021-03-30                1  2021-03-30  2021-12-01  121091.46   
96  2021-04-05                1  2021-04-05  2021-09-30  929631.00   
97  2021-04-13                1  2021-04-13  2021-12-01    9183.33   
98  2021-04-13                1  2021-04-13  2021-12-01    3309.16   
99  2021-04-27                1  2021-04-27  2021-12-01  510436.00   

    enforcement     amount        bg  
0             1   25000.00  0.050000  
1             1  373500.00  0.400014  
2             0    6256.26  0.050000  
3             1   19878.00  0.055968  
4             1   19878.00  0.051229  
..          ...        ...       ...  
95            0   36509.99  0.301508  
96            1  597620.41  0.642858  
97            0    2755.00  0.300000  
98            0     992.75  0.300001  
99            1  153130.80  0.300000  

[100 rows x 12 columns]

In [ ]:
data.tail()

In [76]:
data['st date'] = data['st date'].astype('datetime64[ns]')
data['end date'] = data['end date'].astype('datetime64[ns]')

In [77]:
date_list = pd.date_range('01.01.2019', '01.01.2023', freq='M')

In [78]:
date_list

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31',
               '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31'],
              dtype='datetime64[ns]', freq='M')

In [79]:
t = (data.iloc[1])

In [107]:
t['amount']

373500.0

In [108]:
d = list(map(lambda x: datetime.datetime(2019,6,25)<= x<= datetime.datetime(2021,12,31),date_list))

In [109]:
def check(st, end):
    return list(map(lambda x: st<= x <= end, date_list))

In [110]:
t_arr = np.zeros(len(date_list))

In [111]:
t_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [113]:
for r in data.iterrows():
    t_arr+=np.array(check(r[1]['st date'], r[1]['end date'])) * r[1]['amount']

In [114]:
t_arr

array([       0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,  6344689.63      , 16313096.98      ,
       16752487.24      , 16909572.78      , 17412264.63      ,
       18419243.18      , 17757868.46      , 17305918.44000001,
       17957601.09      , 17964412.74      ,  8134818.28      ,
        4215745.81      ,  4278976.29      ,  3527067.95      ,
        1007022.9       ,   834572.46      ,   645189.39      ,
         645189.39      ,   580610.57      ,   437693.91      ,
         437693.91      ,   437693.91      ,   437693.91      ,
         437693.91      ,   368644.94   

In [106]:
np.round(t_arr)

array([       0.,        0.,        0.,        0.,        0.,        0.,
              0.,        0.,        0.,        0.,        0.,        0.,
              0.,        0.,        0.,        0.,        0.,        0.,
              0.,        0.,        0.,        0.,  6344690., 16313097.,
       16752487., 16909573., 17412265., 18419243., 17757868., 17305918.,
       17957601., 17964413.,  8134818.,  4215746.,  4278976.,  3527068.,
        1007023.,   834572.,   645189.,   645189.,   580611.,   437694.,
         437694.,   437694.,   437694.,   437694.,   368645.,   368645.])

In [90]:
import matplotlib.pyplot as plt